-- CTU Argao campus navigation: buildings as Room.building + imagePath (place under public/campus/navigation/).
-- collegeId is null so all colleges can schedule; chairman RLS still allows SELECT campus-wide.

insert into public."Room" (id, code, building, floor, capacity, type, "collegeId", "imagePath", "displayName")
values
  ('room-ssf-01', 'Room 01', 'Shared Service Facility for Handbloom Weaving', 1, 20, 'Showroom', null, 'campus/navigation/ShowRoom.HEIC', 'Show Room'),
  ('room-ssf-02', 'Room 02', 'Shared Service Facility for Handbloom Weaving', 1, 15, 'Workshop', null, 'campus/navigation/Embroidery.HEIC', 'Embroidery'),
  ('room-ssf-03', 'Room 03', 'Shared Service Facility for Handbloom Weaving', 2, 24, 'Conference', null, 'campus/navigation/ConferenceRoom.HEIC', 'Conference Room'),
  ('room-ssf-04', 'Room 04', 'Shared Service Facility for Handbloom Weaving', 2, 20, 'Workshop', null, 'campus/navigation/IMG_4473.HEIC', 'Garments Room'),
  ('room-ssf-05', 'Room 05', 'Shared Service Facility for Handbloom Weaving', 2, 12, 'Storage', null, 'campus/navigation/ThreadRoom.HEIC', 'Thread Room'),
  ('room-ssf-06', 'Room 06', 'Shared Service Facility for Handbloom Weaving', 3, 20, 'Studio', null, 'campus/navigation/StudioRoom.HEIC', 'Studio Room'),
  ('room-ssf-07', 'Room 07', 'Shared Service Facility for Handbloom Weaving', 3, 18, 'Laboratory', null, 'campus/navigation/FoodLab.HEIC', 'Food Laboratory'),
  ('room-mini-01', 'Mini Hotel 101', 'Mini Hotel', 1, 10, 'Facility', null, 'campus/navigation/MiniHotel.HEIC', null),
  ('room-mini-02', 'Mini Hotel 201', 'Mini Hotel', 2, 10, 'Facility', null, 'campus/navigation/MiniHotel.HEIC', null),
  ('room-hm-dept', 'HM Department', 'HM Department', 1, 30, 'Office', null, 'campus/navigation/HMDepartment.HEIC', null),
  ('room-chapel-01', 'Chapel', 'Chapel', 1, 200, 'Chapel', null, 'campus/navigation/Chapel.HEIC', null),
  ('room-cote-101', 'COTE 101', 'COTE Building', 1, 8, 'Office', null, 'campus/navigation/COTEDean''sOffice.HEIC', 'COTE Dean''s Office'),
  ('room-cote-102', 'COTE 102', 'COTE Building', 1, 24, 'Laboratory', null, 'campus/navigation/FABLab.HEIC', 'FAB Lab'),
  ('room-cote-103', 'COTE 103', 'COTE Building', 1, 24, 'Laboratory', null, 'campus/navigation/W.S.M.&ErgonomicsLab.HEIC', 'W.S.M. & Ergonomics Lab'),
  ('room-cote-104', 'COTE 104', 'COTE Building', 1, 24, 'Laboratory', null, 'campus/navigation/GTLab2.HEIC', 'GT Lab 2'),
  ('room-cote-105', 'COTE 105', 'COTE Building', 1, 24, 'Laboratory', null, 'campus/navigation/GTLab1.HEIC', 'GT Lab 1'),
  ('room-cote-201', 'COTE 201', 'COTE Building', 2, 12, 'Office', null, 'campus/navigation/BITFacultyRoom.HEIC', 'BIT Faculty Office'),
  ('room-cote-202', 'COTE 202', 'COTE Building', 2, 24, 'Laboratory', null, 'campus/navigation/ETLab1.HEIC', 'ET Lab 01 Automation Lab'),
  ('room-cote-203', 'COTE 203', 'COTE Building', 2, 24, 'Laboratory', null, 'campus/navigation/ETLab2.HEIC', 'ET Lab 02'),
  ('room-cote-204', 'COTE 204', 'COTE Building', 2, 24, 'Laboratory', null, 'campus/navigation/ETLab3.HEIC', 'ET Lab 03 Digital Communication Lab'),
  ('room-cote-205', 'COTE 205', 'COTE Building', 2, 24, 'Laboratory', null, 'campus/navigation/DTLab1.HEIC', 'DT Lab 01 (CAD)'),
  ('room-cote-206', 'COTE 206', 'COTE Building', 2, 24, 'Laboratory', null, 'campus/navigation/DTLab2.HEIC', 'DT Lab 02'),
  ('room-cote-207', 'COTE 207', 'COTE Building', 2, 24, 'Laboratory', null, 'campus/navigation/DTLab3.HEIC', 'DT Lab 03'),
  ('room-cote-301', 'COTE 301', 'COTE Building', 3, 12, 'Office', null, 'campus/navigation/BSITFaculty.HEIC', 'BSIT Faculty Office'),
  ('room-cote-302', 'COTE 302', 'COTE Building', 3, 40, 'Computer Lab', null, 'campus/navigation/ITLab4.HEIC', 'IT Lab 04'),
  ('room-cote-303', 'COTE 303', 'COTE Building', 3, 40, 'Computer Lab', null, 'campus/navigation/ITLab3.HEIC', 'IT Lab 03'),
  ('room-cote-304', 'COTE 304', 'COTE Building', 3, 40, 'Computer Lab', null, 'campus/navigation/IT Lab2.HEIC', 'IT Lab 02'),
  ('room-cote-305', 'COTE 305', 'COTE Building', 3, 40, 'Computer Lab', null, 'campus/navigation/ITLab1.HEIC', 'IT Lab 01'),
  ('room-cote-306', 'COTE 306', 'COTE Building', 3, 30, 'Laboratory', null, 'campus/navigation/CTLab2.HEIC', 'CT Lab 02'),
  ('room-cote-307', 'COTE 307', 'COTE Building', 3, 30, 'Laboratory', null, 'campus/navigation/CTLab1.HEIC', 'CT Lab 01'),
  ('room-cote-401', 'COTE 401', 'COTE Building', 4, 12, 'Office', null, 'campus/navigation/CAFEFaculty.HEIC', 'CAFE Faculty'),
  ('room-cote-402', 'COTE 402', 'COTE Building', 4, 24, 'Laboratory', null, 'campus/navigation/Forestry.HEIC', 'Forestry Lab 1'),
  ('room-cote-403', 'COTE 403', 'COTE Building', 4, 24, 'Laboratory', null, 'campus/navigation/Forestry.HEIC', 'Forestry Lab 2'),
  ('room-cote-404', 'COTE 404', 'COTE Building', 4, 24, 'Laboratory', null, 'campus/navigation/ForestryLab3.HEIC', 'Forestry Lab 3'),
  ('room-cote-405', 'COTE 405', 'COTE Building', 4, 24, 'Laboratory', null, 'campus/navigation/Forestry.HEIC', 'Forestry Lab 4'),
  ('room-cote-406', 'COTE 406', 'COTE Building', 4, 30, 'Laboratory', null, 'campus/navigation/CTLab4.HEIC', 'CT Lab 04'),
  ('room-cote-407', 'COTE 407', 'COTE Building', 4, 30, 'Laboratory', null, 'campus/navigation/CTLab3.HEIC', 'CT Lab 03'),
  ('room-coed-101', 'Room 101', 'COED Building', 1, 30, 'Office', null, 'campus/navigation/AccreditationRoom.HEIC', 'Accreditation Room'),
  ('room-coed-102', 'Room 102', 'COED Building', 1, 30, 'Laboratory', null, 'campus/navigation/COEDLab1.HEIC', 'COED Lab 1'),
  ('room-coed-103', 'Room 103', 'COED Building', 1, 30, 'Laboratory', null, 'campus/navigation/COEDLab2.HEIC', 'COED Lab 2'),
  ('room-coed-104', 'Room 104', 'COED Building', 1, 30, 'Laboratory', null, 'campus/navigation/COEDLab3.HEIC', 'COED Lab 3'),
  ('room-coed-200', 'Room 200', 'COED Building', 2, 8, 'Office', null, 'campus/navigation/TempFacultyRoom.HEIC', 'Temp Faculty Room'),
  ('room-coed-201', 'Room 201', 'COED Building', 2, 40, 'Lecture', null, 'campus/navigation/2ndFloor.HEIC', null),
  ('room-coed-300', 'Room 300', 'COED Building', 3, 12, 'Office', null, 'campus/navigation/EDUCFaculty.HEIC', 'EDUC Faculty'),
  ('room-coed-400', 'Room 400', 'COED Building', 4, 12, 'Office', null, 'campus/navigation/CASBAELFaculty.HEIC', 'CAS / BAEL Faculty Room'),
  ('room-ab-01', 'AB 01', 'Admin Building', 1, 6, 'Office', null, 'campus/navigation/Cashier''sOffice.JPG', 'Cashier Office'),
  ('room-ab-02', 'AB 02', 'Admin Building', 1, 8, 'Office', null, 'campus/navigation/Accounting&BudgetOffice.JPG', 'Accounting and Budget Office'),
  ('room-ab-04', 'AB 04', 'Admin Building', 1, 10, 'Office', null, 'campus/navigation/Registrar.JPG', 'Registrar'),
  ('room-ab-05', 'AB 05', 'Admin Building', 1, 8, 'Office', null, 'campus/navigation/MISOffice.JPG', 'MIS Office'),
  ('room-ab-07', 'AB 07', 'Admin Building', 2, 8, 'Office', null, 'campus/navigation/HRMO.JPG', 'HRMO'),
  ('room-ab-08', 'AB 08', 'Admin Building', 2, 8, 'Office', null, 'campus/navigation/DOI.JPG', 'Procurement / DOI Office'),
  ('room-st-201', 'ST 201', 'Science and Technology Building', 2, 30, 'Laboratory', null, 'campus/navigation/ST201.JPG', 'LAB ST 201 Biology'),
  ('room-st-202', 'ST 202', 'Science and Technology Building', 2, 30, 'Laboratory', null, 'campus/navigation/ST202.JPG', 'LAB ST 202 Chemistry'),
  ('room-st-203', 'ST 203', 'Science and Technology Building', 2, 30, 'Laboratory', null, 'campus/navigation/ST203.JPG', 'LAB ST 203 Physics'),
  ('room-ag-ca1', 'Room CA 1', 'Agriculture Building', 1, 40, 'Lecture', null, 'campus/navigation/CA-1.JPG', null),
  ('room-ag-ca2', 'Room CA 2', 'Agriculture Building', 1, 40, 'Lecture', null, 'campus/navigation/CA2(CropProtectionClassroom).JPG', 'CA 2 Crop Protection'),
  ('room-lib-01', 'Library L1', 'Library', 1, 80, 'Library', null, 'campus/navigation/Library1.JPG', null),
  ('room-acad-01', 'ACAD 01', 'ACAD Bldg. Pres. Diosdado Macapagal Academic', 1, 50, 'Lecture', null, 'campus/navigation/ACAD.JPG', null),
  ('room-bio-01', 'Biodiversity 101', 'Biodiversity', 1, 30, 'Laboratory', null, 'campus/navigation/Biodiversity.HEIC', null)
on conflict (code) do update set
  building = excluded.building,
  floor = excluded.floor,
  capacity = excluded.capacity,
  type = excluded.type,
  "collegeId" = excluded."collegeId",
  "imagePath" = excluded."imagePath",
  "displayName" = excluded."displayName";
