insert into public."College" (id, code, name) values ('col-cafe', 'CAFE', 'College of Forestry and Environmental Sciences') on conflict (code) do nothing;
insert into public."Program" (id, code, name, "collegeId") values ('prog-bs-envsci', 'BSENVS', 'Bachelor of Science in Environmental Science', 'col-cafe') on conflict (code) do nothing;
insert into public."Section" (id, "programId", name, "yearLevel", "studentCount") values ('sec-bsenvs-1a', 'prog-bs-envsci', 'BSENVS-1A', 1, 32) on conflict (id) do nothing;
insert into public."Section" (id, "programId", name, "yearLevel", "studentCount") values ('sec-bsenvs-1b', 'prog-bs-envsci', 'BSENVS-1B', 1, 32) on conflict (id) do nothing;
insert into public."Section" (id, "programId", name, "yearLevel", "studentCount") values ('sec-bsenvs-2a', 'prog-bs-envsci', 'BSENVS-2A', 2, 32) on conflict (id) do nothing;
insert into public."Section" (id, "programId", name, "yearLevel", "studentCount") values ('sec-bsenvs-2b', 'prog-bs-envsci', 'BSENVS-2B', 2, 32) on conflict (id) do nothing;
insert into public."Section" (id, "programId", name, "yearLevel", "studentCount") values ('sec-bsenvs-3a', 'prog-bs-envsci', 'BSENVS-3A', 3, 32) on conflict (id) do nothing;
insert into public."Section" (id, "programId", name, "yearLevel", "studentCount") values ('sec-bsenvs-4a', 'prog-bs-envsci', 'BSENVS-4A', 4, 32) on conflict (id) do nothing;
insert into public."Subject" (id, code, subcode, title, "lecUnits", "lecHours", "labUnits", "labHours", "programId", "yearLevel", semester) values
  ('sub-bsenvs-encsc111', 'BSENVS-ENCSC111', null, 'Inorganic Chemistry (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-encsc111l', 'BSENVS-ENCSC111L', null, 'Inorganic Chemistry (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-gec-mmw', 'BSENVS-GEC-MMW', null, 'Mathematics in the Modern World', 3, 3, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-gec-us', 'BSENVS-GEC-US', null, 'Understanding the Self', 3, 3, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-gec-pc', 'BSENVS-GEC-PC', null, 'Purposive Communication', 3, 3, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-gec-rph', 'BSENVS-GEC-RPH', null, 'Readings in Philippine History', 3, 3, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-pathfit-1', 'BSENVS-PATHFIT-1', null, 'Physical Activities Towards Health and Fitness 1', 2, 2, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-nstp-1', 'BSENVS-NSTP-1', null, 'National Service Training Program 1', 3, 3, 0, 0, 'prog-bs-envsci', 1, 1),
  ('sub-bsenvs-encsc122', 'BSENVS-ENCSC122', null, 'Organic Chemistry (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-encsc122l', 'BSENVS-ENCSC122L', null, 'Organic Chemistry (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-encsm123', 'BSENVS-ENCSM123', null, 'College Algebra', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-gec-sts', 'BSENVS-GEC-STS', null, 'Science, Technology and Society', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-gec-aa', 'BSENVS-GEC-AA', null, 'Art Appreciation', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-gec-lie', 'BSENVS-GEC-LIE', null, 'Living in the IT Era', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-gec-tcw', 'BSENVS-GEC-TCW', null, 'The Contemporary World', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-pathfit-2', 'BSENVS-PATHFIT-2', null, 'Physical Activities Towards Health and Fitness 2', 2, 2, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-nstp-2', 'BSENVS-NSTP-2', null, 'National Service Training Program 2', 3, 3, 0, 0, 'prog-bs-envsci', 1, 2),
  ('sub-bsenvs-encsc214', 'BSENVS-ENCSC214', null, 'Analytical Chemistry (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-encsc214l', 'BSENVS-ENCSC214L', null, 'Analytical Chemistry (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-encsm215', 'BSENVS-ENCSM215', null, 'Trigonometry', 3, 3, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-gec-e', 'BSENVS-GEC-E', null, 'Ethics', 3, 3, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-gee-pic', 'BSENVS-GEE-PIC', null, 'Philippine Indigenous Communities', 3, 3, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-gee-gsps', 'BSENVS-GEE-GSPS', null, 'Gender & Society with Peace Studies', 3, 3, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-gec-lwr', 'BSENVS-GEC-LWR', null, 'Life and Works of Rizal', 3, 3, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-pathfit-3', 'BSENVS-PATHFIT-3', null, 'Physical Activities Towards Health and Fitness 3', 2, 2, 0, 0, 'prog-bs-envsci', 2, 1),
  ('sub-bsenvs-encsb227', 'BSENVS-ENCSB227', null, 'General Biology (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-encsb227l', 'BSENVS-ENCSB227L', null, 'General Biology (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-encsm228', 'BSENVS-ENCSM228', null, 'Calculus', 3, 3, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-encse229', 'BSENVS-ENCSE229', null, 'Geology and Soil Science', 3, 3, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-encsp2210', 'BSENVS-ENCSP2210', null, 'Mechanics and Thermodynamics (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-encsp2210l', 'BSENVS-ENCSP2210L', null, 'Mechanics and Thermodynamics (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-enm221', 'BSENVS-ENM221', null, 'Waste Management', 3, 3, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-gee-pee', 'BSENVS-GEE-PEE', null, 'People and the Earth''s Ecosystem', 3, 3, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-pathfit-4', 'BSENVS-PATHFIT-4', null, 'Physical Activities Towards Health and Fitness 4', 2, 2, 0, 0, 'prog-bs-envsci', 2, 2),
  ('sub-bsenvs-encsb3111', 'BSENVS-ENCSB3111', null, 'Genetics (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-encsb3111l', 'BSENVS-ENCSB3111L', null, 'Genetics (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-encsm3112', 'BSENVS-ENCSM3112', null, 'Environmental Statistics (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-encsm3112l', 'BSENVS-ENCSM3112L', null, 'Environmental Statistics (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-encse3113', 'BSENVS-ENCSE3113', null, 'Freshwater Resources Management (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-encse3113l', 'BSENVS-ENCSE3113L', null, 'Freshwater Resources Management (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-ens312', 'BSENVS-ENS312', null, 'Biodiversity Conservation (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-ens312l', 'BSENVS-ENS312L', null, 'Biodiversity Conservation (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-ens313', 'BSENVS-ENS313', null, 'Soil and Water Conservation (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-ens313l', 'BSENVS-ENS313L', null, 'Soil and Water Conservation (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 1),
  ('sub-bsenvs-encsb3214', 'BSENVS-ENCSB3214', null, 'General Ecology (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-encsb3214l', 'BSENVS-ENCSB3214L', null, 'General Ecology (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-enm323', 'BSENVS-ENM323', null, 'Watershed Management (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-enm323l', 'BSENVS-ENM323L', null, 'Watershed Management (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-enm324', 'BSENVS-ENM324', null, 'Coastal and Marine Management (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-enm324l', 'BSENVS-ENM324L', null, 'Coastal and Marine Management (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-ens315', 'BSENVS-ENS315', null, 'Environmental Chemistry (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-ens315l', 'BSENVS-ENS315L', null, 'Environmental Chemistry (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-ens316', 'BSENVS-ENS316', null, 'Research Methods with GIS', 3, 3, 0, 0, 'prog-bs-envsci', 3, 2),
  ('sub-bsenvs-eia', 'BSENVS-EIA', null, 'The EIA System (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 4, 1),
  ('sub-bsenvs-eial', 'BSENVS-EIAL', null, 'The EIA System (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 4, 1),
  ('sub-bsenvs-enm415', 'BSENVS-ENM415', null, 'Environmental Auditing (Lec)', 2, 2, 0, 0, 'prog-bs-envsci', 4, 1),
  ('sub-bsenvs-enm415l', 'BSENVS-ENM415L', null, 'Environmental Auditing (Lab)', 1, 0, 0, 3, 'prog-bs-envsci', 4, 1),
  ('sub-bsenvs-thesis1', 'BSENVS-THESIS1', null, 'Thesis Proposal', 3, 3, 0, 0, 'prog-bs-envsci', 4, 1),
  ('sub-bsenvs-ens428', 'BSENVS-ENS428', null, 'Environmental Monitoring (Lec)', 3, 3, 0, 0, 'prog-bs-envsci', 4, 2),
  ('sub-bsenvs-ens428l', 'BSENVS-ENS428L', null, 'Environmental Monitoring (Lab)', 2, 0, 0, 6, 'prog-bs-envsci', 4, 2),
  ('sub-bsenvs-thesis2', 'BSENVS-THESIS2', null, 'Thesis Writing 2', 3, 3, 0, 0, 'prog-bs-envsci', 4, 2)
on conflict (code) do update set title = excluded.title, "lecUnits" = excluded."lecUnits", "lecHours" = excluded."lecHours", "labUnits" = excluded."labUnits", "labHours" = excluded."labHours", "programId" = excluded."programId", "yearLevel" = excluded."yearLevel", semester = excluded.semester;
